### ISSUE TITLE
Amharic: question

### ISSUE THREAD

**Issue by yosiasz** [UniversalDependencies/UD_Amharic-Inku#1]
hello @dan-zeman just starting out on this project. This is all new to me but I had started the following effort a while back.

https://github.com/geeztypes/Amharic_TreeBank/blob/main/am_geeztypes-train.conllu

Any feedback would really be appreciated? Am I heading in the right direction? I am using an automated process and then correcting things manually. The corrections are persisted in a local sqlite db, so that next run with more batch of data knows the correction etc. Thanks!

**Comment by dan-zeman** [comment]
Well, your strategy of repeated automated processing and manual checking sounds reasonable, but there is not much annotation in the file you link to, and I do not read Amharic, so it is difficult to say anything about it. But at least the UPOS tags might be a step in the right direction. Note that without the dependency relations it is not a treebank and it cannot become part of a UD release.

**Comment by yosiasz** [comment]
Ok, that gives me a good direction to head to. This was something I was playing around with just to familiarize myself with whole ud ecosystem 

Thanks!

**Comment by yosiasz** [comment]
@dan-zeman back after a year 3 year hiatus :( 

question on the following header with Ancora spanish train data

```
# global.Entity = eid-etype-head-other
# newdoc id = 3LB-CAST-104_c-1
# sent_id = 3LB-CAST-104_c-1-s1
```

Is there a specific nomenclature I need to follow for the header?

Thanks!

**Comment by martinpopel** [comment]
- The `globale.Entity` header should only be used when annotating coreference in the [CorefUD](https://ufal.mff.cuni.cz/corefud) format using [Entity](https://universaldependencies.org/misc.html#entity) in MISC.
- `sent_id` is required in UD treebanks as [documented](https://universaldependencies.org/format.html#sentence-boundaries-and-comments).
-  It is recommended to mark [document and paragraph boundaries](https://universaldependencies.org/format.html#paragraph-and-document-boundaries) using `newdoc` and `newpar` headers respectively. The format of these IDs is not prescribed, but I suggest to keep the IDs brief but informative. Many treebanks use the  document name (i.e.`newdoc` ID) as a prefix for `sent_id`.
