### ISSUE TITLE
Amharic: tokenization and segmentation

### ISSUE THREAD

**Issue by yosiasz** [UniversalDependencies/UD_Amharic-Inku#3]
Greetings,

In UD Guidelines it states "Hence, morphological features are encoded as properties of words and there is no attempt at segmenting words into morphemes"

Would the following qualify as segmenting words into morphemes?

አስቴር እንደሄደች ነገረችኝ።
Aster told me she left.

እንደ-ሄደ-ች - that went she
ነገረ-ች-ኝ - told she me

or does one keep it tidy and simple as this? (DEPREL might be inaccurate please disregard)
```
# sent_id = am-train-001-s3
# text = አስቴር እንደሄደች ነገረችኝ ።
# translit = āsitēri inidehēdechi negerechinyi.
1	አስቴር	አስቴር	PROPN	PROPN	_	0	obj	_	Translitāsitēri|LTranslit=āsitēri
2	እንደሄደች	እንደሄደች	VERB	VERB	_	1	det	_	Translit=inidehēdechi|LTranslit=inidehēdechi
3	ነገረችኝ	ንነገረችኝ	VERB	VERB	_	1	case	_	Translit=negerechinyi|LTranslit=negerechinyi
4	።	።	PUNCT	PUNCT	_	1	punct	_	Translit=.|LTranslit=.
```

and not

```
# sent_id = am-train-001-s3
# text = አስቴር እንደሄደች ነገረችኝ ።
# translit = āsitēri inidehēdechi negerechinyi.
1	አስቴር	አስቴር	PROPN	PROPN	_	0	obj	_	Translitāsitēri|LTranslit=āsitēri
2-4	እንደሄደች	እንደሄደች	VERB	VERB	_	1	det	_	Translit=inidehēdechi|LTranslit=inidehēdechi
2	እንደ እንደ VERB	VERB	_	1	det	_	Translit=inide|LTranslit=inide
3	ሄደ  ሄደ VERB	VERB	_	1	det	_	Translit=hēde|LTranslit=hēde
4	ች   ች ?	?	_	1	det	_	Translit=chi|LTranslit=chi
5-7 ነገረችኝ	ንነገረችኝ	VERB	VERB	_	1	case	_	Translit=negerechinyi|LTranslit=negerechinyi
4	።	።	PUNCT	PUNCT	_	1	punct	_	Translit=.|LTranslit=.
```
Thanks!

**Comment by dan-zeman** [comment]
> Would the following qualify as segmenting words into morphemes?

Yes, I think it would. When the verb inflects following the number, person and gender of the subject, we do not segment the verb but we annotate the form with the features of the number / person / gender:

* ሄድኩ `Mood=Ind|Number=Sing|Person=1|Tense=Past|VerbForm=Fin` _hedəku_ "I went"
* ሄድህ `Gender=Masc|Mood=Ind|Number=Sing|Person=2|Tense=Past|VerbForm=Fin` _hedəhə_ "you went"
* ሄድሽ `Gender=Fem|Mood=Ind|Number=Sing|Person=2|Tense=Past|VerbForm=Fin` _hedəšə_ "you went"
* ሄደ `Gender=Masc|Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin` _hedä_ "he went"
* ሄደች `Gender=Fem|Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin` _hedäčə_ "she went"
* ሄደን `Mood=Ind|Number=Plur|Person=1|Tense=Past|VerbForm=Fin` _hedänə_ "we went"
* ሄዳችሁ `Mood=Ind|Number=Plur|Person=2|Tense=Past|VerbForm=Fin` _hedačəhu_ "you went"
* ሄዳቸው `Mood=Ind|Number=Plur|Person=3|Tense=Past|VerbForm=Fin` _hedačäwə_ "they went"

**Comment by yosiasz** [comment]
got it

ሄዱ is interesting one

applies for they went but also used for honorific verb conjugation.

not sure what that could be tagged as for ex. grandpa left for the hospital

**Comment by dan-zeman** [comment]
> ሄዱ is interesting one
> 
> applies for they went but also used for honorific verb conjugation.
> 
> not sure what that could be tagged as for ex. grandpa left for the hospital

This is tricky. You could distinguish the honorific case by using `Number=Sing` together with `Polite=Form`. But you could also say that this is simply a plural form of the verb, which can be used in singular context (so it will be always tagged `Number=Plur`). The latter is easier to annotate, the former provides more search options for the user. As a matter of fact, we have a similar phenomenon in Czech and we do not disambiguate the honorific usage (i.e., we adopt the second approach above).
